import React, { useState } from 'react';
import { 
  FileCode, Terminal, Download, Check, Clipboard, 
  HelpCircle, Server, Info
} from 'lucide-react';

export default function ApiDocs() {
  const [copiedText, setCopiedText] = useState<string | null>(null);

  const handleCopy = (text: string, id: string) => {
    navigator.clipboard.writeText(text);
    setCopiedText(id);
    setTimeout(() => setCopiedText(null), 2000);
  };

  // 1. DYNAMIC POSTMAN COLLECTION EXPORT GENERATOR
  const downloadPostman = () => {
    const postmanJson = {
      info: {
        _postman_id: "72d96c92-fb21-4f1b-a5de-eb8957829107",
        name: "GitHub Profile Analyzer API",
        description: "Postman Collection for testing the backend Express endpoints of the GitHub Profile Analyzer. Includes schema queries, profile catalogs, and single user search analysis. Requires a valid Firebase Auth Bearer ID Token.",
        schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
      },
      item: [
        {
          name: "Health State",
          request: {
            method: "GET",
            header: [],
            url: {
              raw: "{{BASE_URL}}/api/health",
              host: ["{{BASE_URL}}"],
              path: ["api", "health"]
            },
            description: "Check server status."
          }
        },
        {
          name: "Fetch Profile Catalog",
          request: {
            auth: {
              type: "bearer",
              bearer: [
                {
                  key: "token",
                  value: "{{FIREBASE_ID_TOKEN}}",
                  type: "string"
                }
              ]
            },
            method: "GET",
            header: [],
            url: {
              raw: "{{BASE_URL}}/api/profiles",
              host: ["{{BASE_URL}}"],
              path: ["api", "profiles"]
            },
            description: "Get all historical profile analytics. Returns profile scores and developer styles."
          }
        },
        {
          name: "Fetch Single Analyzed Profile",
          request: {
            auth: {
              type: "bearer",
              bearer: [
                {
                  key: "token",
                  value: "{{FIREBASE_ID_TOKEN}}",
                  type: "string"
                }
              ]
            },
            method: "GET",
            header: [],
            url: {
              raw: "{{BASE_URL}}/api/profiles/subhranshuchoudhury",
              host: ["{{BASE_URL}}"],
              path: ["api", "profiles", "subhranshuchoudhury"]
            },
            description: "Fetch singular profile metrics by case-insensitive username match."
          }
        },
        {
          name: "Analyze profile (Perform Run)",
          request: {
            auth: {
              type: "bearer",
              bearer: [
                {
                  key: "token",
                  value: "{{FIREBASE_ID_TOKEN}}",
                  type: "string"
                }
              ]
            },
            method: "POST",
            header: [
              {
                key: "Content-Type",
                value: "application/json",
                type: "text"
              }
            ],
            body: {
              mode: "raw",
              raw: JSON.stringify({ username: "subhranshuchoudhury" }, null, 2)
            },
            url: {
              raw: "{{BASE_URL}}/api/analyze",
              host: ["{{BASE_URL}}"],
              path: ["api", "analyze"]
            },
            description: "Downloads profile metadata and languages from GitHub public endpoints, generates full profile insights, summarizes detailed talent reviews, and registers details securely in PostgreSQL."
          }
        }
      ],
      event: [
        {
          listen: "prerequest",
          script: {
            type: "text/javascript",
            exec: [""]
          }
        },
        {
          listen: "test",
          script: {
            type: "text/javascript",
            exec: [""]
          }
        }
      ],
      variable: [
        {
          key: "BASE_URL",
          value: window.location.origin,
          type: "string"
        },
        {
          key: "FIREBASE_ID_TOKEN",
          value: "YOUR_JWT_ID_TOKEN_HERE",
          type: "string"
        }
      ]
    };

    const blob = new Blob([JSON.stringify(postmanJson, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'github_analyzer_postman_collection.json';
    link.click();
    URL.revokeObjectURL(url);
  };

  // 2. SQL SCHEMA DUMP GENERATOR (MySQL Only)
  const downloadSqlSchema = () => {
    const rawSql = `-- MySQL DDL Schema Export for GitHub Profile Analyzer API
-- Automatically generated by AI Studio Workspace

-- Table structure for "users"
CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  uid VARCHAR(255) NOT NULL UNIQUE, -- Synchronized with Firebase Auth UID
  email VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Table structure for "analyzed_profiles"
CREATE TABLE IF NOT EXISTS analyzed_profiles (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE, -- Case-insensitive canonical GitHub username
  name TEXT,
  avatar_url TEXT,
  bio TEXT,
  location TEXT,
  company TEXT,
  blog TEXT,
  github_url TEXT,
  followers INT DEFAULT 0 NOT NULL,
  following INT DEFAULT 0 NOT NULL,
  public_repos INT DEFAULT 0 NOT NULL,
  total_stars INT DEFAULT 0 NOT NULL,
  total_forks INT DEFAULT 0 NOT NULL,
  avg_repo_size INT DEFAULT 0 NOT NULL, -- in KB
  profile_score INT DEFAULT 0 NOT NULL, -- Core custom algorithm index
  developer_style VARCHAR(255), -- developer archetypes
  top_repos JSON, -- list of top-starred public repos
  language_breakdown JSON, -- percentages
  ai_summary TEXT, -- detailed analysis report
  user_id INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- Indexes to maximize coordinate match speed
CREATE INDEX idx_profiles_username ON analyzed_profiles (username);
CREATE INDEX idx_profiles_score ON analyzed_profiles (profile_score DESC);
CREATE INDEX idx_users_uid ON users (uid);
`;

    const blob = new Blob([rawSql], { type: 'text/sql' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'github_analyzer_mysql_schema.sql';
    link.click();
    URL.revokeObjectURL(url);
  };

  const curlAnalyze = `curl -X POST "${window.location.origin}/api/analyze" \\
  -H "Authorization: Bearer <YOUR_FIREBASE_ID_TOKEN>" \\
  -H "Content-Type: application/json" \\
  -d '{"username": "subhranshuchoudhury"}'`;

  const curlProfiles = `curl -X GET "${window.location.origin}/api/profiles" \\
  -H "Authorization: Bearer <YOUR_FIREBASE_ID_TOKEN>"`;

  const curlSingle = `curl -X GET "${window.location.origin}/api/profiles/subhranshuchoudhury" \\
  -H "Authorization: Bearer <YOUR_FIREBASE_ID_TOKEN>"`;

  return (
    <div className="space-y-8 font-sans pb-16">
      {/* Header and Download Bar */}
      <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div className="space-y-1">
          <h1 className="text-xl font-bold text-slate-900 flex items-center gap-2">
            <Server className="h-5 w-5 text-indigo-600" />
            Express API Specification & Download Exports
          </h1>
          <p className="text-sm text-slate-500">
            Export submission-ready deliverables or inspect API parameters.
          </p>
        </div>

        <div className="flex flex-wrap gap-2">
          <button
            onClick={downloadSqlSchema}
            className="inline-flex items-center gap-1.5 text-[11px] md:text-xs font-semibold px-3.5 py-2 border border-indigo-200 text-indigo-700 bg-indigo-50/20 hover:bg-indigo-50 rounded-xl transition-colors cursor-pointer"
          >
            <Download className="h-3 w-3 text-indigo-500" />
            MySQL Script
          </button>

          <button
            onClick={downloadPostman}
            className="inline-flex items-center gap-1 text-[11px] md:text-xs font-semibold px-2.5 py-2 border border-transparent text-white bg-slate-900 hover:bg-slate-800 rounded-xl shadow-xs transition-colors cursor-pointer"
          >
            <Download className="h-3 w-3 text-amber-400" />
            Postman Collection
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Left column: Endpoint details */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs">
            <h2 className="text-lg font-bold text-slate-900 mb-4 border-b border-slate-100 pb-3 flex items-center gap-2">
              <FileCode className="h-5 w-5 text-slate-500" />
              Developer API Endpoints Reference
            </h2>

            <div className="space-y-6 mt-4">
              {/* Endpoint 1: Analyze */}
              <div className="border border-slate-200 rounded-xl p-4 space-y-3">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold font-mono tracking-wider px-2.5 py-1 bg-amber-50 text-amber-700 border border-amber-100 rounded-md uppercase">
                    POST
                  </span>
                  <span className="text-[14px] font-mono font-bold text-slate-900">/api/analyze</span>
                  <span className="text-[11px] font-semibold text-indigo-600 bg-indigo-50/50 px-2 py-0.5 rounded-full ml-auto">
                    Requires Auth
                  </span>
                </div>
                <p className="text-xs text-slate-600">
                  Fetches profile details and commits calculated analyzer metrics to MySQL database.
                </p>
                <div className="bg-slate-50 p-3 rounded-lg border border-slate-200/85">
                  <p className="text-[11px] font-bold text-slate-400 font-mono uppercase mb-1">Payload Body</p>
                  <pre className="text-xs text-slate-700 font-mono">
                    {`{\n  "username": "subhranshuchoudhury"\n}`}
                  </pre>
                </div>
              </div>

              {/* Endpoint 2: Get all */}
              <div className="border border-slate-200 rounded-xl p-4 space-y-3">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold font-mono tracking-wider px-2.5 py-1 bg-emerald-50 text-emerald-700 border border-emerald-100 rounded-md uppercase">
                    GET
                  </span>
                  <span className="text-[14px] font-mono font-bold text-slate-900">/api/profiles</span>
                  <span className="text-[11px] font-semibold text-indigo-600 bg-indigo-50/50 px-2 py-0.5 rounded-full ml-auto">
                    Requires Auth
                  </span>
                </div>
                <p className="text-xs text-slate-600">
                  Loads all stored profile evaluations. Ordered dynamically by custom Profile Score desc.
                </p>
              </div>

              {/* Endpoint 3: Get single */}
              <div className="border border-slate-200 rounded-xl p-4 space-y-3">
                <div className="flex items-center gap-2">
                  <span className="text-xs font-bold font-mono tracking-wider px-2.5 py-1 bg-emerald-50 text-emerald-700 border border-emerald-100 rounded-md uppercase">
                    GET
                  </span>
                  <span className="text-[14px] font-mono font-bold text-slate-900">/api/profiles/:username</span>
                  <span className="text-[11px] font-semibold text-indigo-600 bg-indigo-50/50 px-2 py-0.5 rounded-full ml-auto">
                    Requires Auth
                  </span>
                </div>
                <p className="text-xs text-slate-600">
                  Retrieves complete stored analytical history (including language bytes and Top 5 repositories) for single user.
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Right column: Copiable cURL console */}
        <div className="space-y-6">
          <div className="bg-white border border-slate-200 rounded-2xl p-6 shadow-xs flex flex-col justify-between h-full">
            <div>
              <h2 className="text-lg font-bold text-slate-900 mb-2 flex items-center gap-2">
                <Terminal className="h-5 w-5 text-slate-700" />
                Copiable testing cURLs
              </h2>
              <p className="text-xs text-slate-500 mb-6">
                Copy and run directly in terminal. Remember to replace the Bearer Token.
              </p>

              <div className="space-y-5">
                {/* cURL 1 */}
                <div className="space-y-1.5">
                  <div className="flex justify-between items-center text-xs font-bold text-slate-800">
                    <span>1. Analyze & save profile</span>
                    <button 
                      onClick={() => handleCopy(curlAnalyze, 'analyze')}
                      className="text-slate-400 hover:text-indigo-600 flex items-center gap-1 cursor-pointer"
                    >
                      {copiedText === 'analyze' ? <Check className="h-3 w-3 text-emerald-500" /> : <Clipboard className="h-3 w-3" />}
                      {copiedText === 'analyze' ? 'Copied' : 'Copy'}
                    </button>
                  </div>
                  <pre className="p-3 bg-slate-950 text-indigo-300 font-mono text-[10.5px] rounded-lg overflow-x-auto whitespace-pre leading-relaxed border border-slate-850">
                    {curlAnalyze}
                  </pre>
                </div>

                {/* cURL 2 */}
                <div className="space-y-1.5">
                  <div className="flex justify-between items-center text-xs font-bold text-slate-800">
                    <span>2. Fetch all profiles</span>
                    <button 
                      onClick={() => handleCopy(curlProfiles, 'profiles')}
                      className="text-slate-400 hover:text-indigo-600 flex items-center gap-1 cursor-pointer"
                    >
                      {copiedText === 'profiles' ? <Check className="h-3 w-3 text-emerald-500" /> : <Clipboard className="h-3 w-3" />}
                      {copiedText === 'profiles' ? 'Copied' : 'Copy'}
                    </button>
                  </div>
                  <pre className="p-3 bg-slate-950 text-indigo-300 font-mono text-[10.5px] rounded-lg overflow-x-auto whitespace-pre leading-relaxed border border-slate-850">
                    {curlProfiles}
                  </pre>
                </div>

                {/* cURL 3 */}
                <div className="space-y-1.5">
                  <div className="flex justify-between items-center text-xs font-bold text-slate-800">
                    <span>3. Drill-down profile details</span>
                    <button 
                      onClick={() => handleCopy(curlSingle, 'single')}
                      className="text-slate-400 hover:text-indigo-600 flex items-center gap-1 cursor-pointer"
                    >
                      {copiedText === 'single' ? <Check className="h-3 w-3 text-emerald-500" /> : <Clipboard className="h-3 w-3" />}
                      {copiedText === 'single' ? 'Copied' : 'Copy'}
                    </button>
                  </div>
                  <pre className="p-3 bg-slate-950 text-indigo-300 font-mono text-[10.5px] rounded-lg overflow-x-auto whitespace-pre leading-relaxed border border-slate-850">
                    {curlSingle}
                  </pre>
                </div>
              </div>
            </div>

            <div className="mt-8 bg-indigo-50 border border-indigo-100/50 p-4 rounded-xl flex items-start gap-2.5">
              <Info className="h-4.5 w-4.5 text-indigo-500 shrink-0 mt-0.5" />
              <div className="text-xs text-indigo-600 leading-normal">
                <strong>How to get the Bearer Token?</strong> In the active application header, open the <strong>User Token</strong> dropdown, where you can instantly view and copy your valid runtime JWT Token for local testing!
              </div>
            </div>
          </div>
        </div>

      </div>

      {/* EXTREMELY HELPFUL INTERVIEW PREPARATION COMPANION */}
      <div className="bg-slate-900 border border-slate-850 rounded-2xl p-6 md:p-8 text-white space-y-6">
        <div className="border-b border-slate-800 pb-4">
          <span className="text-[10px] uppercase tracking-widest text-indigo-400 font-mono font-bold">Interview Prep Suite</span>
          <h2 className="text-lg md:text-xl font-bold tracking-tight mt-1 flex items-center gap-2">
            <HelpCircle className="h-5 w-5 text-indigo-400" />
            🎓 Technical Interview Alignment Guide (Why MySQL?)
          </h2>
          <p className="text-xs text-slate-400 mt-1">
            Questions, answers, and strategies to confidently present this backend submission to your hiring panel.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8">
          
          <div className="space-y-4">
            <div className="bg-slate-950/60 p-5 rounded-xl border border-slate-850 space-y-2">
              <span className="text-[10px] font-mono font-black text-indigo-300">Q1. Why is MySQL chosen as the database?</span>
              <p className="text-xs text-slate-300 leading-relaxed">
                <strong>Answer:</strong> "I chose <strong>MySQL</strong> because it is an extremely reliable and ubiquitous relational database for web applications. It handles read-heavy workloads incredibly well, which is perfect for an API that serves analyzed profiles.
              </p>
              <p className="text-xs text-slate-300 leading-relaxed">
                Using <strong>Drizzle ORM</strong> with MySQL provides a highly performant, type-safe data modeling layer with lightning-fast query compilation and native upserts (using <code className="text-indigo-400 font-mono text-[10.5px]">onDuplicateKeyUpdate</code>) for seamless data integration."
              </p>
            </div>

            <div className="bg-slate-950/60 p-5 rounded-xl border border-slate-850 space-y-2">
              <span className="text-[10px] font-mono font-black text-indigo-300">Q2. How is authorization handled to prevent database breach?</span>
              <p className="text-xs text-slate-300 leading-relaxed">
                <strong>Answer:</strong> "I implemented safe **Token-based REST authentication** using **Firebase ID Tokens (JWT)**. On Google OAuth Sign-In, the client obtains a valid cryptographic JWT from Firebase.
              </p>
              <p className="text-xs text-slate-300 leading-relaxed">
                Every API call sends this token in the <code className="text-indigo-400 font-mono text-[10.5px]">Authorization: Bearer</code> header. The Express server validates this token using the server-side SDK to check timestamps, signatures, and ensure the coordinator exists before processing any database insertions."
              </p>
            </div>
          </div>

          <div className="space-y-4">
            <div className="bg-slate-950/60 p-5 rounded-xl border border-slate-850 space-y-2">
              <span className="text-[10px] font-mono font-black text-indigo-300">Q3. How does this application leverage MySQL-specific schema capabilities?</span>
              <p className="text-xs text-slate-300 leading-relaxed">
                <strong>Answer:</strong> "This application uses MySQL's native <strong>JSON</strong> storage data types to hold the language usage breakdowns and top-starred repository lists.
              </p>
              <p className="text-xs text-slate-300 leading-relaxed">
                This allows us to store complex nested data efficiently, and it is fully typed in our ORM schema using <code className="text-indigo-400 font-mono text-[10.5px]">json().$type&lt;...&gt;()</code>. This keeps our relational schema simple while retaining the flexibility of document-oriented storage within a robust RDBMS like MySQL."
              </p>
            </div>

            <div className="bg-slate-950/60 p-5 rounded-xl border border-slate-850 space-y-2">
              <span className="text-[10px] font-mono font-black text-indigo-300">Q4. How does the custom "Profile Score" algorithm work?</span>
              <p className="text-xs text-slate-300 leading-relaxed">
                <strong>Answer:</strong> "The score is derived from an algorithm I designed to reflect real developer productiveness. It combines public repo presence (20%), follower traction (20%), accumulated stars (30%), forks count (20%), and average codebase size (10%), normalizing the outcome out of 100 points."
              </p>
            </div>
          </div>

        </div>
      </div>

    </div>
  );
}
